#
# Module manifest for module 'CommonResources'
# Generated by: Lucas Ivan Benchat Parra
# Generated on: 17/12/2023
#

@{

	# Script module or binary module file associated with this manifest.
	RootModule = 'CommonResources.psm1'

	# Version number of this module.
	ModuleVersion = '1.0.0'

	# Supported PSEditions.
	CompatiblePSEditions = @("Desktop", "Core")

	# ID used to uniquely identify this module
	GUID = 'cd6377c4-1556-48ac-ab40-402b0414b18a'

	# Author of this module
	Author = 'Lucas Ivan Benchat Parra'

	# Copyright statement for this module
	Copyright = '(c) Lucas Ivan Benchat Parra. All rights reserved.'

	# Description of the functionality provided by this module
	Description = 'Provides common functions for my PowerShell back-up scripts.'
	
	# Minimum version of the PowerShell engine required by this module.
	PowerShellVersion = '5.1'

	# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
	# FunctionsToExport = @()

	# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
	# CmdletsToExport = @()

	# Variables to export from this module.
	# VariablesToExport = '*'

	# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
	# AliasesToExport = @()

	# DSC resources to export from this module.
	# DscResourcesToExport = @()

	# List of all files packaged with this module.
	FileList = @("CommonResources.psm1")

	# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
	PrivateData = @{

	    PSData = @{

		# A URL to the license for this module.
		LicenseUri = 'https://github.com/foopsss/scripts/blob/main/LICENSE'

		# A URL to the main website for this project.
		ProjectUri = 'https://github.com/foopsss/scripts'

		# Flag to indicate whether the module requires explicit user acceptance for install/update/save
		RequireLicenseAcceptance = $false

	    # End of PSData hashtable
	    }

	# End of PrivateData hashtable
	}

}